[env]
TERM = "xterm-256color"

[font]
size = 7

[font.normal]
family = "Liberation Mono"
style = "Regular"

[font.bold]
family = "Liberation Mono"
style = "Bold"

[font.italic]
family = "Liberation Mono"
style = "Italic"

[font.bold_italic]
family = "Liberation Mono"
style = "Bold Italic"

[scrolling]
history = 100000

[general]
import = [
	"~/.config/alacritty/themes/solarized_dark.toml" 
]
